### ISSUE TITLE
Make watcher handle rapid file changes better

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#101]
The watcher's current behavior is to react to any change in a bundle's files, with the exception of the contents of the `view` folder. This is suboptimal, as many events such installing/uninstalling a bundle or running `git pull` will cause the parser to run dozens or hundreds of times in a fraction of a second. This can actually crash or deadlock small VPSes with limited RAM, as each cycle of the parser could potentially spin up an instance of npm and/or bower.

The watcher should instead have some kind of backoff algorithm:
 1. The watcher detects a file change, and it triggers the parser to reload the bundle
 2. A timer is started
 3. If any further changes happen while this timer is running, the timer is reset and nothing else happens.
 4. Once the timer expires, and if any changes beyond the initial one were made, reload the bundle once more.

This has the benefit of still being instant for developers making small changes to single files, while not crashing the system when dragging dozens or hundreds of files into the `bundles` folder. The duration of the timer doesn't need to be long, I think 100ms might be a good starting point to test with.

**Comment by MattMcNam** [comment]
Fixed in #103
