### ISSUE TITLE
Handling File Uploads

### ISSUE THREAD

**Issue by hostdos** [nodecg/nodecg#104]
Assuming some bundles in the future will allow File-uploads (images most likely), where should those be saved on disk?
Should each Bundle handle the file saving itself, or will there eventually be a dedicated folder for shared bundle-connected files in nodecg itself?

**Comment by techguydave** [comment]
I personally think it makes sense to have a single upload folder. If you have, for instance, a logo that three bundles need, no sense in creating three copies in three distant folders. Update the logo once, all of the bundles see the change, no hunting down where they're all located.

**Comment by Lange** [comment]
Right now bundle can implement file uploading itself via express PUT routes and connect-busboy.

However, I agree that file uploading could be made easier and that we should consider making part of the API.

My initial thought is that files would be uploaded to `nodecg/files/:bundleName` on the disk. We could also make a boolean toggle for whether or not to serve this data via HTTP via the endpoint `/files/:bundleName`.

As for @synth3tk's use case, I think that if multiple bundles are relying on shared code and/or assets then that shared stuff should be broken out into a helper bundle. The end result would be the same, bundles wishing to use this logo could link `/files/helper-bundle/logo.png` in their HTML. See @SupportClass for some examples for helper bundles.
