### ISSUE TITLE
Login options

### ISSUE THREAD

**Issue by MattMcNam** [nodecg/nodecg#12]
Currently, NodeCG only supports Steam OpenID as a method of authentication. This should be extended to support more OpenID providers, as well as username/password combos unique to each NCG installation, with accompanying admin UI.

**Comment by MattMcNam** [comment]
~~No more moves beyond 0.5.0 now that we have socket.io 1.x working~~

I lied, will require more time to ensure a secure & user friendly design :disappointed:

**Comment by Lange** [comment]
Closing in favor of #139
