### ISSUE TITLE
Provide an easier way to disable bundles

### ISSUE THREAD

**Issue by denolfe** [nodecg/nodecg#124]
When developing a bundle, it would be nice to have a way to easily enable/disable other bundles.

Current workarounds:
- Move bundle to a folder adjacent to `bundles`
- Rename `nodecg.json` to something else ie. `nodecg.json.disabled`
- Add `Enabled` property in `nodecg.json` that is `true` by default but can be flipped to `false`

Ideas:
- Build a command into the nodecg-cli to do one of the above workarounds programmatically

Open to other ideas/solutions

**Comment by thesupremecommander** [comment]
I thought about it a while before, and I think one of the better solutions could be to have a file that NodeCG checks for (something like `bundle.disabled`). That way, NodeCG doesn't have to parse the entire JSON file just to check if disabled, and enabling/disabling it is as simple as renaming or adding/deleting a file.

**Comment by denolfe** [comment]
@thesupremecommander I definitely like that idea. No interfering with the package itself or folder locations. Probably only 2 or so locations in the code that would need to be altered.

**Comment by Seldszar** [comment]
Why not providing a special `bundles` field on the global NodeCG config file?
This field contains a `disabled` with an array of bundle names and used during bundles directory discovery.

**Comment by denolfe** [comment]
@Seldszar I like this idea better than the last! Reminds me of how Sublime Text handles disabled packages with their Package Control plugin. One central location and no need for extra files.

**Comment by Lange** [comment]
This has been resolved by #248! Thanks to @madmatt for the PR. This feature was long overdue.
