### ISSUE TITLE
socket.io: "connection refused" when running with defaults on a hosted setup

### ISSUE THREAD

**Issue by Diftraku** [nodecg/nodecg#125]
After installing nodecg 0.6.1 using the nodecg-cli (from npm) and browsing to the dashboard, socket.io returns connection refused while the nodecg instance is being hosted on another computer:

```
GET http://localhost:9090/socket.io/?EIO=3&transport=polling&t=1442763099372-60 net::ERR_CONNECTION_REFUSED
Request.create @ socket.io.js:2919
Request @ socket.io.js:2842
XHR.request @ socket.io.js:2773
XHR.doPoll @ socket.io.js:2803
Polling.poll @ socket.io.js:3192
Polling.doOpen @ socket.io.js:3136
Transport.open @ socket.io.js:2313
Socket.open @ socket.io.js:1743
Socket @ socket.io.js:1625
Socket @ socket.io.js:1560
Manager.open.Manager.connect @ socket.io.js:299
(anonymous function) @ socket.io.js:564
```

This took me a while to figure even though `localhost` was staring at me in the eye. As a suggestion, shouldn't socket.io use the URL for hints where the nodecg is being hosted if defaults are being used?

**Comment by Seldszar** [comment]
By default, if an URL is not provided on client constructor, Socket.io use the current hostname (with port), simply becoming this line:

```
window.socket = io(); // equivalent to io.connect()
```

I think remove this parameter would be cool to resolve this kind of error, especially when we have a special kind of setup.

**Comment by Lange** [comment]
Sorry this took me so darn long to get around to doing. @Seldszar, you were totally right! Works like a charm.

**Comment by Seldszar** [comment]
I'm glad my solution has been useful for you (and totally forgot to make a PR when the issue was found) :smile_cat:
