### ISSUE TITLE
'nodecg/logger' is not in the npm registry

### ISSUE THREAD

**Issue by ChapDaddy65** [nodecg/nodecg#130]
I just installed nodecg-cli.

when I tried to git a fresh copy of nodecg using `nodecg setup` I get this error:

```
$ nodecg setup
Cloning NodeCG... done!
Installing production npm dependencies... failed!
Error: Command failed: npm install --production
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'nodecg/logger' is not in the npm registry.
***npm ERR! 404 You should bug the author to publish it***
npm ERR! 404 It was specified as a dependency of 'nodecg'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 10.0.10586
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd D:\nodecg
npm ERR! node -v v5.3.0
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\nodecg\npm-debug.log
npm ERR! not ok code 0
```

When performing a normal `git clone` I download nodecg fine, but when I `npm install --production` I get the same message, but with a different dependency required, instead of `/logger` I get `/bundle-manager`

I am very new to nodecg, so I might be missing something, but not sure what at this point?

Thank you. :)

**Comment by MattMcNam** [comment]
NPM version 2 is required (Does Node v5 ship with NPM v1 on Windows, or not update old versions?)

`npm install -g npm@2` should allow you to install the dependencies

**Comment by Lange** [comment]
To clarify, npm version 2 or above is required. I recommend using version 3, it's real nice!

**Comment by ChapDaddy65** [comment]
wow, such an oversight!

I updated node thinking it would update npm as well, turns out it does not in my case. I updated npm and it worked.

Thank you.
