### ISSUE TITLE
Assets Assignable Attribute 

### ISSUE THREAD

**Issue by goldbattle** [nodecg/nodecg#208]
When creating a package.json with just a `soundCues` section specified, the "Sounds" options is not created in the assets tab. When I add a random value under `assetCategories` both that added category and the "Sounds" option will appear. With the asset section removed from the json the asset page is just blank.

``` json
     "soundCues": [
      {
        "name": "sub",
        "assignable": true,
        "defaultFile": "sounds/sub.ogg"
      },
      {
        "name": "tip",
        "assignable": true,
        "defaultFile": "sounds/tip.ogg"
      },
      {
        "name": "cut",
        "assignable": true,
        "defaultFile": "sounds/cut.ogg"
      },
      {
        "name": "out",
        "assignable": true,
        "defaultFile": "sounds/out.ogg"
      }
    ],
    "assetCategories": [
      {
        "name": "testing",
        "title": "Testing",
        "allowedTypes": [
          "ogg",
          "mp3"
        ]
      }
    ]
```

**Comment by Lange** [comment]
I will look into this when I can, which unfortunately might be a while. I have a lot going on! In the meantime, PRs are more than welcome if you can figure out and resolve the issue before I have a chance to get to it.

Thanks for your patience even though I took a few days to respond. Busy times!

**Comment by Chr12t0pher** [comment]
:+1:

I've got some free time over the weekend, I'll try and have a look at it - no guarantees.
