### ISSUE TITLE
Replicant Change Event Not Firing

### ISSUE THREAD

**Issue by BossOfGames** [nodecg/nodecg#216]
Hey All. I am having a problem with using replicants. In the AGDQ 2016 layout, I liked the use of them to A) keep info global, B) use in place of message events (which can get ridiculous). The problem I have been having is that yes I am changing the replicant value properly as to the tutorials, in practice it is not working correctly.

For Starters, here is the Dashboard HTML and JS

`<!DOCTYPE html>
<head>
    <script src="components/webcomponentsjs/webcomponents-lite.min.js"></script>

```
<link rel="import" href="components/polymer/polymer.html">
<link rel="import" href="components/paper-input/paper-input.html">
<link rel="import" href="components/paper-input/paper-textarea.html">
<link rel="import" href="components/paper-dropdown-menu/paper-dropdown-menu.html">
<link rel="import" href="components/paper-menu/paper-menu.html">
<link rel="import" href="components/paper-item/paper-item.html">
<link rel="import" href="components/paper-button/paper-button.html">
<link rel="import" href="components/iron-flex-layout/classes/iron-flex-layout.html">
<link rel="stylesheet" href="css/main.css">
```

</head>

<body>
    <div class="layout horizontal">
        <div class="flex" style="padding-right: 5px">
            <paper-input type="text" label="REF Number" id="trak-ref-number"></paper-input>
            <paper-button raised class="blue" id="trak-pull">Pull Data</paper-button>
            <paper-input type="text" label="Round Information" id="round"></paper-input>
            <paper-input type="text" label="Team 1 Score" id="team-1-score"></paper-input>
            <paper-input type="text" label="Team 2 Score" id="team-2-score"></paper-input>

```
        <paper-button raised class="blue" id="update">Update</paper-button>
        <paper-button raised class="green" id="show">Show</paper-button>
        <paper-button raised class="red" id="hide">Hide</paper-button>

        <div class="layout horizontal">
        </div>
    </div>
</div>
<script src="js/overwatch-scoreboard.js" defer></script>
```

</body>
</html>
`
`(function () {
    'use strict';

```
// get the team scores
var team1score = document.getElementById('team-1-score');
var team2score = document.getElementById('team-2-score');

// Round Information
var team1name = document.getElementById('team1name');
var team2name = document.getElementById('team2name');

var roundinfo = document.getElementById('round');
// buttons
var pulldata = document.getElementById('trak-pull');
var show = document.getElementById('show');
var hide = document.getElementById('hide');
var update = document.getElementById('update').addEventListener('click', updateGraphic, false);

// UPDATE SCORES ON GRAPHIC COMMAND
var scores = nodecg.Replicant('scores');
var showing = nodecg.Replicant('scoreboardShowing');

function updateGraphic() {
    scores.value = [
        team1score.value,
        team2score.value,
        roundinfo.value

    ];
    console.log("Update Graphic Event Fired");
}
show.addEventListener('click', function() {
    showing.value = true;
});
showing.on('change', function (newVal, oldVal) {
    if (newVal) {

    }
})
```

})();`

Here is the graphic HTML and JS.

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.0/TweenMax.min.js"></script>

```
<link rel="stylesheet" href="css/Scoreboard.css">
```

</head>

<body>
    <div id="center">
        <div id="TITLE_BOX"></div>
        <div id="EVENT_TITLE">OW FREE AGENT INVITATIONAL</div>
        <div id="LINE"></div>
        <div id="ROUND"></div>
        <div id="T1C2"><div id="T1C2_Shadow"></div></div>
        <div id="T2C2"><div id="T2C2_Shadow"></div></div>
    </div>
    <div id="team1">
        <div id="T1C1"></div>
        <div id="T1B1"></div>
        <div id="TEAM_ONE_NAME">TEAM ONE</div>
        <div id="T1_SCORE"></div>
    </div>
    <div id="team2">
        <div id="T2C1"></div>
        <div id="T2B1"></div>
        <div id="TEAM_TWO_NAME">TEAM TWO</div>
        <div id="T2_SCORE"></div>
    </div>
    <script src="js/trak-e-scoreboard.js"></script>
</body>
</html>`

`(function () {

```
'use strict';

// Lets define our elements

var EVENT_NAME = document.getElementById('EVENT_TITLE');
var ROUND = document.getElementById('ROUND');
var T1NAME = document.getElementById('TEAM_ONE_NAME');
var T2NAME = document.getElementById('TEAM_TWO_NAME');
var T1SCORE = document.getElementById('T1_SCORE');
var T2SCORE = document.getElementById('T2_SCORE');

// Define the divs we will be animating.

var center = document.getElementById('center');
var team1 = document.getElementById('team1');
var team2 = document.getElementById('team2');

var tl = new TimelineLite({autoRemoveChildren: true});

// define our showing and hiding triggers
var showing = nodecg.Replicant('scoreboardShowing');
var scores = nodecg.Replicant('scores');

scores.on('change', function (newVal,oldVal) {
    var values = newVal.value;
    try {
        T1SCORE.value = values[0];
        T2SCORE.value = values[1];
        ROUND.value = values[2];
    }
    catch (exception) {
        console.log(exception);
    }
})
showing.on('change', function (newVal,oldVal) {
    if (newVal) {
        tl.call(function() {
            // set all the information to display
            var values = scores.value;

            T1SCORE.value = values[0];
            T2SCORE.value = values[1];
            ROUND.value = values[2];

        }, null, null, '+=0.1');

    }
});
```

})();`

What is exactly going on here other than my lack of coding style?

**Comment by Lange** [comment]
This issue is hard to read. It seems that some of it is malformatted. Refer to GitHub's "[Mastering Markdown](https://guides.github.com/features/mastering-markdown/" page for some tips on how to use GitHub-flavored markdown to format posts.

**Comment by BossOfGames** [comment]
Well the good news is that I got it resolved. It was faulty coding on my part of the scoreboard graphic js.
