### ISSUE TITLE
Error with running nodecg?

### ISSUE THREAD

**Issue by KnoxVegas** [nodecg/nodecg#241]
os: Windows 10
node: 7.2.0
nodecg: latest

error:
"""
λ node index.js
[nodecg] No config found, using defaults.
info: [nodecg/lib/server] Starting NodeCG 0.8.5 (Running on Node.js v7.2.0)
Verifying/installing npm deps for bundle toth4-overlay... failed!
Error: Command failed: npm install --production
node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@3.1.2 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (P:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "P:\\nodejs\\node.exe" "P:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "P:\\nodejs\\node.exe" "C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport
node-pre-gyp ERR! node -v v7.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
npm WARN toth4-overlay@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "P:\\nodejs\\node.exe" "P:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! serialport@3.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@3.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\npm-debug.log

    at checkExecSyncError (child_process.js:488:13)
    at execSync (child_process.js:528:13)
    at C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\lib\npm_installer.js:27:4
    at fs.readdirSync.forEach.bundleFolderName (C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\index.js:144:4)
    at Array.forEach (native)
    at EventEmitter.module.exports.init (C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\index.js:111:30)
    at EventEmitter.module.exports.start (C:\Users\cwilson\Desktop\NodeJS\nodecg\lib\server\index.js:92:16)
    at Object.<anonymous> (C:\Users\cwilson\Desktop\NodeJS\nodecg\index.js:29:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
UNCAUGHT EXCEPTION! NodeCG will now exit.
Error: [toth4-overlay] Failed to install npm dependencies: Command failed: npm install --production
node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.1.2/serialport-v3.1.2-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@3.1.2 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (P:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "P:\\nodejs\\node.exe" "P:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "P:\\nodejs\\node.exe" "C:\\Users\\cwilson\\Desktop\\NodeJS\\nodecg\\bundles\\toth4-overlay\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\node_modules\serialport
node-pre-gyp ERR! node -v v7.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
npm WARN toth4-overlay@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "P:\\nodejs\\node.exe" "P:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! serialport@3.1.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@3.1.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cwilson\Desktop\NodeJS\nodecg\bundles\toth4-overlay\npm-debug.log

    at C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\lib\npm_installer.js:40:11
    at C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\lib\npm_installer.js:43:6
    at fs.readdirSync.forEach.bundleFolderName (C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\index.js:144:4)
    at Array.forEach (native)
    at EventEmitter.module.exports.init (C:\Users\cwilson\Desktop\NodeJS\nodecg\node_modules\@nodecg\bundle-manager\index.js:111:30)
    at EventEmitter.module.exports.start (C:\Users\cwilson\Desktop\NodeJS\nodecg\lib\server\index.js:92:16)
    at Object.<anonymous> (C:\Users\cwilson\Desktop\NodeJS\nodecg\index.js:29:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
"""

**Comment by Lange** [comment]
Ah, so the problem here isn't with NodeCG itself. The bundle you have installed, `toth4-overlay`, has some native npm dependencies which require compilation. For this compilation to succeed, you must have the appropriate build tools installed. In the past, this has been a massive pain, but now you can just follow the directions to install [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)!

After installing `windows-build-tools`, you may need to either close and re-open your command prompt or restart your PC. If, even after doing that, NodeCG still throws this error on startup, it may be because the way that NodeCG invokes `npm` to install each bundle's dependecies isn't correctly finding the various build tools it needs. If that happens, you can just manually run `npm install` from the `nodecg/bundles/toth4-overlay` folder, rather than relying on NodeCG's automatic npm installation.

**Comment by KnoxVegas** [comment]
Ah that was the fix! Thank you very much for that @Lange should be working like a champ now!  Hopefully I can come up with something just as good as as what you have been doing!
