### ISSUE TITLE
Refactor all instances of `fs.existsSync` and `fs.exists`

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#262]
`existsSync` can often be replaced with something that just attempts to read/write the file directly, and then we can handle any `ENOENT` error that arises. An `express` example:
```js
res.sendFile(fileLocation, err => {
	if (err) {
		if (err.code === 'ENOENT') {
			return res.sendStatus(404);
		}

		nodecg.log.error('Failed to serve cached image:\n', err.stack ? err.stack : err);
		return res.sendStatus(500);
	}
});
```

As for `exists`, I'm pretty sure we don't use it anywhere but it's hella deprecated so we should be sure that we don't use it.

**Comment by MattMcNam** [comment]
Fixed in #278
