### ISSUE TITLE
Evaluate Cypress.io as a replacement for WebDriver.io

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#273]
https://www.cypress.io/

NodeCG's current browser tests are a nightmare. Anything that claims to make them simpler, easier to maintain, and faster to run is worth trying out.

**Comment by Lange** [comment]
I have applied for early access to Cypress. We'll see if I get accepted.

**Comment by MattMcNam** [comment]
Applied earlier too, the GUI not (yet) running on Windows could be a pain though: https://docs.cypress.io/docs/installing-and-running#section-system-requirements

**Comment by Lange** [comment]
Oh, huh. Yeah I hadn't seen that yet. 🤔

**Comment by Lange** [comment]
I finally got access to the Cypress.io beta, but I don't see any time in the near future where I will have enough spare time to evaluate it.

**Comment by Lange** [comment]
It also seems that Windows is still not supported, so we can't use Cypress until that is resolved anyway.

**Comment by Lange** [comment]
Going to just close this. We can re-open once Cypress supports Windows and if we still this it has value for NodeCG.

**Comment by Lange** [comment]
Cypress now supports Windows, and its open-source.
