### ISSUE TITLE
Make end-to-end tests for the Assets system

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#280]
It has none, currently.

**Comment by Lange** [comment]
Now that we have client-side coverage, adding these tests will be a bit more rewarding. It'll also be possible to tell what code paths are still untested.

**Comment by Lange** [comment]
This is important, but I just don't have the will to write more tests right now. This can wait until after 0.9 is out.

**Comment by riktimmondal** [comment]
I will like to work on it can you guide me on this?

**Comment by Lange** [comment]
Hi @riktimmondal!

Great! Here's some links to get you started:

- NodeCG's tests of its Sound system can probably be used as a starting point/reference.
  - https://github.com/nodecg/nodecg/blob/master/test/sounds.js
- To learn how to run the tests locally, check out this link:
  - https://github.com/nodecg/nodecg#running-tests-locally
- If you want to run the tests more quickly, you can run `ava` directly instead of running `npm t`, which also re-builds all of NodeCG before running the tests. If you're changing client-side code then you'll need to do this, but if you're only changing server-side code or the contents of your test files, then you can save time by just running `ava`.
  - You'll first need to install `ava` globally via `npm i -g ava`
  - You can also run specific test files or folders with `ava`. For example, `ava test/sounds.js` will only run that one test file, and `ava test/logger` will run all the tests in the `logger` folder.
  - Check out [`ava`'s docs](https://github.com/avajs/ava) for more info.

**Comment by Lange** [comment]
Done in https://github.com/nodecg/nodecg/commit/dfce675341b61faca92c14d1473c313fc087eb5a
