### ISSUE TITLE
Support multiple .listenFor handlers for a given message

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#298]
The fact that a given message can only have one `.listenFor` handler per message is an artificial limitation that we put in place years ago. There's kind of no good reason for it. Although this is unlikely to break anyone's code, it is still technically a breaking change.

**Comment by Lange** [comment]
As part of this, it probably makes sense to re-write these to use EventEmitter under the hood. We're kind of just re-implementing our own bad version of EventEmitter here.

We already include EventEmitter in the browserified API bundle, so this will not make that any larger. I can't think of any reason not to go ahead and make this change.

**Comment by Lange** [comment]
This is still good to have, but not important enough to warrant delaying 0.9 further for. This can wait.

**Comment by haganbmj** [comment]
Is there a proposed way to handle multiple acknowledgements?
- Take the first acknowledgement.
- Wait for all acknowledges and require all passed?

**Comment by Lange** [comment]
Oh, gosh I hadn't thought about acknowledgements at all. I have no idea what we'd do for those. Hm...

**Comment by haganbmj** [comment]
Yeah, everything was looking EventEmitter-y until I got to Acknowledgements.

**Comment by Lange** [comment]
The only thing I can think of would be to follow the model of `express` middleware. Any piece of middleware in the chain can invoke a `response`, but once a response has been invoked, subsequent attempts to invoke it will throw an error. We'd need to provide some API which can be used to query if an acknowledgement has already been sent or not.
