### ISSUE TITLE
Dashboard panels not recached if bundle directory is a symlink

### ISSUE THREAD

**Issue by atribecalledkwest** [nodecg/nodecg#320]
This appears to be an issue with however chokidar does globbing (more specifically with `**`) which is used in bundle-manager, if your bundle is a symlink to another directory then every change to a dashboard panel's HTML file requires a restart of the server.  This isn't too much of an issue for production, but it is slightly annoying for development.

**Comment by Lange** [comment]
I published a new version of bundle-manager. Give that a shot and reopen if it doesn't fix the issue.
