### ISSUE TITLE
Use nyc's source map support to get accurate stack traces from failed tests

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#336]
See https://github.com/istanbuljs/nyc#accurate-stack-traces-using-source-maps

In the meantime, the local workaround is to just not use `nyc` to run tests if you're doing debugging, just run `ava` directly.

**Comment by Lange** [comment]
I _think_ `nyc` does this by default now? Tentatively closing.

**Comment by Lange** [comment]
Nope, still an issue.

**Comment by Hoishin** [comment]
What stack trace you want to have resolved? I couldn't produce the situation (besides `https://localhost:99999/foobar.js` kind traces, which I don't think can be resolved)

**Comment by Lange** [comment]
Maybe it _is_ fixed now, but the issue was that if a server-side test failed, the stack trace printed by `ava` would show the results from the instrumented code, rather than being mapped to the source code.

**Comment by Lange** [comment]
Stale, closing. Re-open if we discover that this is still a problem
