### ISSUE TITLE
Margin added on <dom-if> elements inside dialogs

### ISSUE THREAD

**Issue by nospoone** [nodecg/nodecg#339]
As the title says, margin is added on `<dom-if>` elements inside dashboard dialog boxes, but outside their `iframe`s.

![](https://files.gitter.im/nodecg/nodecg/pGfG/image.png)

![](https://files.gitter.im/nodecg/nodecg/MLJ8/image.png)

I'd love to take a look at it, if you're willing to point me at the problem. I've looked around but couldn't find much.

**Comment by Lange** [comment]
It comes from these two places:

https://github.com/nodecg/nodecg/blob/master/src/dashboard/elements/ncg-dashboard.html#L358-L360
https://github.com/nodecg/nodecg/blob/master/src/dashboard/elements/ncg-dialog.html#L70-L73

**Comment by nospoone** [comment]
PR submitted: https://github.com/nodecg/nodecg/pull/340

**Comment by Lange** [comment]
Fixed by 7bb2f9fd5d81d4a1bb1c3572206eaaca87e0d2e3
