### ISSUE TITLE
Migrate from bower to yarn or npm

### ISSUE THREAD

**Issue by Nols1000** [nodecg/nodecg#345]
The bower team will display a warning if bower is installed. The warning refers to a [blog post](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) in which they recommend switching from bower to yarn and webpack.

```
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment 
because its dependencies can change. Prevent this by migrating to Yarn: 
https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

I think it would be good to migrate now for two reasons:
1. if the bower team decides to stop supporting bower (which looks like it won't happen now, but it could happen later), the project would not work anymore. If we migrated, we wouldn't have to rely on Bower.
2. all dependencies would be managed by one package manager and could be found in one place.

I would welcome a lively discussion on the issues of whether we should migrate and which package manager to use for the future of this project.

**Comment by Lange** [comment]
Yep, this will be done once Polymer is properly supported on npm. I'd guess it'd be another year or two before things are ready. In the meantime, things will keep working.
