### ISSUE TITLE
`nodecg.log` methods add to the stack, obscuring the source of the call

### ISSUE THREAD

**Issue by alvancamp** [nodecg/nodecg#351]
Using `nodecg.log.info` in a browser context results in a useless stack frame being linked:
![image](https://user-images.githubusercontent.com/873012/33632535-8902978c-d9d3-11e7-8d55-c9817a516771.png)

We can maybe avoid this by altering the stack trace such that Chrome (and other browsers) log the source of the `nodecg.log` invocation, rather than the internal location where we actually call `console.log`.

**Comment by haganbmj** [comment]
Accessing the caller of a function isn't permitted, so even altering the original `arguments` object to prefix it wasn't working for me (shift all the arguments back, add a 0 index as a prefix, update `arguments.length`, pass that to `console.*`). 

Here's a simple solution that just logs the caller inline by constructing an Error and getting the stack trace from that.
https://github.com/haganbmj/nodecg/commit/a631c05d758a4446798ee40828adc6f4ccf33917

<img width="796" alt="firefox-log" src="https://user-images.githubusercontent.com/15820761/37632653-b0eb3b34-2bc5-11e8-94b7-1d2396450bfb.png">

It's worth noting that console.error attaches a stack trace already, so at worst just telling people to use that if they really want line numbers is something.

**Comment by alvancamp** [comment]
Going to close this as being unrealistic to fix for now.
