### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by ZeroEnna** [nodecg/nodecg#361]
Hello everyone,

I wanted to install NodeCG, but I get an error:

` git clone git@github.com:github:Lange/json-schema-lib    is not a valid repository name
`

What can I do?

Thank you in advance

**Comment by Lange** [comment]
What version of Node.js and npm do you have installed? I recommend using the latest release of Node.js 8, which will come with a recent version of npm 5.

**Comment by ZeroEnna** [comment]
Okay it seems to only be a problem when running this on a Raspberry Pi. Installing it on an Ubuntu system works fine but comes with other problems :)
