### ISSUE TITLE
`npm test` makes Git diff

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#367]
- OS: macOS Sierra 10.12.6
- `node -v`: v8.9.4
- `npm -v`: 5.6.0

Running `npm test` locally makes Git diff. I wonder if it is expected.

Raw git diff (really long): https://gist.github.com/Hoishin/f725b8e59f10ed24ee1cc378385b795d

**Comment by Hoishin** [comment]
More user-friendly git diff

https://github.com/Hoishin/nodecg/commit/97a063d546850b22f46d160889ea9448457699f3

**Comment by Lange** [comment]
This is somewhat expected, because `npm test` also runs `npm run build`, due to the `pretest` script: https://github.com/nodecg/nodecg/blob/master/package.json#L68

**Comment by Lange** [comment]
I don't get the same results when running on Windows, which maybe means that something about OSX is causing more files to appear changed than they would on Windows. I'm unsure if anything can be done about this.

**Comment by Hoishin** [comment]
I forgot you used Windows. It'd make sense for different OS to make such difference. I think it should be fine if there isn't any big difference between them.

BTW, those image diffs are ¯\_(ツ)_/¯

**Comment by Lange** [comment]
We'll close this for now, but we'll be on the lookout for ways to maybe make this more consistent across other platforms.
