### ISSUE TITLE
Don't crash when a bundle's package.json is temporarily invalid

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#373]
Here's the sequence of events:

- Load NodeCG normally with your bundle. Everything's fine at this stage.
- Some time later, edit your bundle's `package.json` to be invalid.
- NodeCG will immediately crash.

NodeCG is intentionally crashing here, in an attempt to avoid undefined behavior. However, this crash isn't necessary. NodeCG could simply refuse to read the now-invalid `package.json` until it is valid again.

This issue might not sound too severe, but there's actually a chance for this crash to happen every time `git` is used to alter a bundle's `package.json` while NodeCG is running. This actually happened to me at AGDQ 2018. I ran `git pull` to pull some updates, and one of those updates changed `package.json`. 

During the fraction of a second where `git` was updating `package.json`, NodeCG tried to read it, and in that instant it was not valid JSON. NodeCG immediately crashed, and it took me a bit to figure out what was going on.

It's supposed to be pretty safe to update bundles while NodeCG is running, but this current behavior makes it very dangerous.

**Comment by Seldszar** [comment]
Just to be sure, the crash must still occur during launch then show a warning message during bundle changes (during execution), or show a warning message during launch too?

**Comment by Lange** [comment]
For now, leave it as a crash on startup. I think it can be helpful that NodeCG won't let you start with broken bundles.
