### ISSUE TITLE
Test stops in the middle

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#378]
<img width="994" alt="screen shot 2018-02-14 at 20 19 52" src="https://user-images.githubusercontent.com/28832095/36201778-7e318b6e-11c4-11e8-96d5-55ebb0f42561.png">

The test stucks at the job added in https://github.com/nodecg/nodecg/commit/4d42335947fc820895b3a888a31a1fbfbf4989f1 and eventually fails. I'd guess it reload and fail again and again?

**Comment by Lange** [comment]
Interesting. @seldszar, can you take a look?

**Comment by Seldszar** [comment]
Sure.

I see why it's stuck, it simply caused by the new change behavior.

**Comment by Hoishin** [comment]
Oh I just noticed what I said in the first half wasn't right, my bad.
