### ISSUE TITLE
Multi Instance usage of a bundle for different contexts

### ISSUE THREAD

**Issue by TreZc0** [nodecg/nodecg#394]
Based on the Discord discussion:
In some cases, it can be needed to use a dashboard in multiple contexts, i.e. to feed different twitch streams / channels individually at the same time.
Currently, there is no way to handle this without interfering with the other users and the replicants except for multiple copies of one and the same bundle, replicants (or symlinks) which is hard to maintain and rather ressource heavy.

My idea involved something like an alert window on dashboard load with a dropdown for the "bundle-context" if you want that defines the bundle/data-source nodecg is supposed to pull the values from to allow multiple people to use the same dashboard in different contexts, forcing nodecg to create a set multiple replicant-sets for each context without the need of a new bundle.

Not entirely sure if this is too specific to ask for, thats why opening an issue sounds like a solid way to go right now.

**Comment by Lange** [comment]
What is stopping you from implementing this in your bundle's code? This sounds like a very niche use case, and I'm not seeing the value in adding this to the core API at this time.

**Comment by Lange** [comment]
Here's two potential routes:

```js
const chosenNamespace = someFunctionYoullWrite();

// later in your code
const exampleReplicant = nodecg.Replicant('example-replicant', chosenNamespace);
nodecg.listenFor('example-message', chosenNamespace, () => {});
nodecg.sendMessageToBundle('example-message', chosenNamespace, {data: 'foo'});
```

Or:
```js
const chosenNamespace = someFunctionYoullWrite();
nodecg.bundleName = chosenNamespace;

// declare replicants, listeners, and senders like normal
const exampleReplicant = nodecg.Replicant('example-replicant');
nodecg.listenFor('example-message', () => {});
nodecg.sendMessage('example-message', {data: 'foo'});
```

This is just example code that I haven't actually tried. It might not work if you just copy/paste it, but it illustrates the concepts.
