### ISSUE TITLE
v0.9.11: ERR_EMPTY_RESPONSE when loading graphics

### ISSUE THREAD

**Issue by Forceh91** [nodecg/nodecg#400]
I've just done a fresh "install" of NodeCG and made sure NodeJS and npm are all as up to date as they can be.

I've created a very basic bundle with nothing in it other than a single graphic HTML file which does nothing other than create a blank div currently.

My dashboard loads fine but everytime I try and load any graphic at all (even ones that dont exist), Chrome will sit doing nothing for ages and eventually return saying ``ERR_EMPTY_RESPONSE``.

This seems to happen with existing bundles too.

**Comment by Lange** [comment]
Interesting, I've not experienced this issue before. At this time I'm unsure what the cause is, and what the resolution would be.

**Comment by Forceh91** [comment]
It's definitely specific to this install. I have a v0.9.9 install that is running fine. Would a copy of my nodecg folder help at all?

**Comment by atribecalledkwest** [comment]
Almost certainly, a copy of the nodecg folder and whatever bundles you're using (if possible) would be a huge help, and some info on your OS/NodeJS version/etc.

**Comment by Forceh91** [comment]
@atribecalledkwest Do you have somewhere that I could send this to for you to take a look?

**Comment by Forceh91** [comment]
Fixed as of v0.9.12.
