### ISSUE TITLE
Coverage reporting intermittently fails

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#409]
Example: https://travis-ci.org/nodecg/nodecg/builds/402150613#L1245

**Comment by Lange** [comment]
This _might_ be fixed now? Tentatively closing.

I think the issue was being caused by not re-building the client-side API before committing/running tests.

**Comment by Lange** [comment]
Still happens occasionally.

**Comment by Lange** [comment]
Example build output of coverage failing: https://travis-ci.org/nodecg/nodecg/builds/403659243?utm_source=github_status&utm_medium=notification

**Comment by Lange** [comment]
Tracking issue: https://github.com/istanbuljs/nyc/issues/425

**Comment by Hoishin** [comment]
Staling issue, will open if someone encounters again.
