### ISSUE TITLE
Versioned docs on nodecg.com

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#412]
Currently, docs for past versions of NodeCG are not viewable on nodecg.com. They should be.

**Comment by Dan-Shields** [comment]
I'm interested in perusing this, but I'm struggling to think how it can be accomplished. JSDoc [can't be run as library apparently](https://github.com/jsdoc3/jsdoc/pull/548), so I'm guessing it'd probably need a shell script?

Something to build docs based on current codebase, then git reset to version tags (only major changes) and run JSDoc to output into a sub directory. That, or to fetch `lib/api.js` from stored github urls, if we don't care about building old tutorials/READMEs.

An alternative is running JSDoc as a child process, but I'm not sure how advisable that is.

**Comment by Lange** [comment]
I think that the versioned docs should be a complete snapshot of the entire docs (including tutorials and README) as it existed at that time.

JSDoc can be invoked from code using [`exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) or [`execSync`](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options)

Beyond that, I've not put any thought into this. It's entirely possible that our approach of using a JSDoc-based website just isn't compatible with this type of feature. More research is definitely needed.

**Comment by Lange** [comment]
Another thing I just thought of: it'd be good to also have an option to view docs for the latest `master` commit, for folks who are using tip-of-tree builds.

**Comment by Lange** [comment]
After talking about it for a while, we determined that this isn't actually super critical right now. We will re-visit the idea when 2.0 is closer to becoming a reality.
