### ISSUE TITLE
Unlisten Replicant.on('change', cb)

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#428]
Currently, as far as I know, there is no way to remove lister for Replicant.

For example, if you have a component with Replicant event listener set up when mounted, every time the component mounts it adds `'change'` listener. If you could "unlisten" the listener when unmounting, this problem would not happen.

```ts
export class Twitter extends React.Component {
	cb = (newVal: Tweets) => {
		console.log(newVal[0].text);
	};
	listener: EventListener | null = null

	componentDidMount() {
		this.listener = tweetsRep.on('change', this.cb)
	}

	render() {
		return (
			<Container>
				<Label>ツイート表示管理</Label>
				<Empty>表示するツイートがありません</Empty>
			</Container>
		);
	}

	componentWillUnmount() {
		// Node EventEmitter way
		tweetsRep.removeListener('change', this.cb)
		tweetsRep.removeAllListener('change')

		// Also from Node v10
		tweetsRep.off('change', this.cb)
	}
}
```

**Comment by Hoishin** [comment]
Does the Node API work on browser too? At least removeListener was undefined

**Comment by Lange** [comment]
That is very strange. `<nodecg-replicant>` uses `.removeListener`: https://github.com/NodeCGElements/nodecg-replicant/blob/master/nodecg-replicant-targeting.js#L89

**Comment by Hoishin** [comment]
Hmm, I might be doing something wrong. Let me check in a few days

**Comment by Hoishin** [comment]
Yeah that definitely exists. Never mind :P
