### ISSUE TITLE
Write tutorial for using Webpack Dev Server or Parcel to develop bundles

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#430]
Related to #429. I personally have no experience doing this, so this would have to come from someone else.

**Comment by Hoishin** [comment]
Would be worth to make docs for `webpack-serve` now that `webpack-dev-server` is maintenance only now.

**Comment by Lange** [comment]
Noted, I was unaware of `webpack-serve`

**Comment by Lange** [comment]
I'd also accept a `parcel` tutorial. Based on discussions in Discord, it sounds much easier to set up and it works better with NodeCG.

**Comment by Hoishin** [comment]
Side note, webpack-serve is deprecated now (lol), so probably be change back to webpack-dev-server

**Comment by Lange** [comment]
This has been done, forgot to close
