### ISSUE TITLE
Re-write non-Polymer code in TypeScript

### ISSUE THREAD

**Issue by alvancamp** [nodecg/nodecg#431]
I'd like to port all of NodeCG over to TypeScript. Thankfully, we can do this in stages. I currently think a two-stage approach will be best:

1. Port all non-Polymer code
2. Port the remaining code

Stage 2 will be harder, because getting Polymer 2 to play nicely with TypeScript comes with some challenges. We may evaluate moving to Polymer 3 at that time to make the transition easier.

For now, I'm only worried about Stage 1, as that is where the greatest benefit to bundle devs lies.

**Comment by Lange** [comment]
Tagging @Hoishin and @ProbablePrime, as they have experience with both NodeCG and TypeScript, and may be able to offer valuable insight as to how we should best go about this (Others are welcome to chime in as well).

**Comment by Hoishin** [comment]
I wonder what would be the good comfortable way to reference the types from the bundle. The best is probably installing NodeCG as dependency, but it is not ready yet for that. But that is one thing to consider.

Also skimming through the source code, I have a feeling that it might require huge refactoring due to the way NodeCG builds the objects/classes. And there might be a need of breaking change because of this.

**Comment by ProbablePrime** [comment]
Hoishin is right. TypeScript usually dislikes default exports and in the traditional JS/Node world they are used a ton.

For actually doing it. The typescript compiler can be configured to work in mixed codebases. You can start with a build pipeline that does the necessary TS compilation and it will just ignore/move the JS files. Then as you re-write file by file to TS you'll get the TypeScript Benefits.

Additionally if you're using doc blocks a lot then: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html should be an awesome way to speed this up.

**Comment by Hoishin** [comment]
It looks like Polymer is moving its way to lit-html. Even Polymer recommends using lit-html and lit-element.
I'm curious if NodeCG will continue using Polymer or move onto another library.

**Comment by Lange** [comment]
I'm not 100% sure what the plan is for the Polymer project, and will wait and see before making a decision.

My guess right now is that Polymer 4's structure is still being decided upon. I think the plan is to have Polymer continue to exist, and be based on `lit-html`/`lit-element`. I base this guess on the fact that the Polymer team has been posting job listings on Twitter, and they wouldn't be expanding that team if they were winding the project down.

I agree that `lit-html`/`lit-element` looks very good, and my ideal outcome would be that Polymer 4 is based on it.

I think we'll get more information on the future of Polymer and `lit-html` at the upcoming Chrome Dev Summit in November. Based on what we hear and see there, we can get a better sense of what the roadmaps for Polymer and `lit-html` are. Whatever ends up happening, I don't want to use `lit-html` until it is at a 1.0 release.

**Comment by Hoishin** [comment]
Also, this conversation isn't much related to the issue itself. I was going to talk about the Polymer side refactoring :P

**Comment by Lange** [comment]
Here's my current thoughts:

- I still think we can and should start by focusing on porting only the server-side code to TypeScript.
- After that, we can use the techniques developed at GDQ and Blizzard to port the frontend Polymer 2 code to TypeScript.
- We need to migrate away from Polymer 2 at some point. 
	- The main reason I see for migrating is that it is not possible to get full type checking of HTML markup with Polymer 2 (HTML Imports are also deprecated, but their polyfill is pretty simple so relying on that polyfill for a while doesn't worry me at this time).
	- It is currently only possible to achieve type checking of HTML markup with TSX, which pretty much means we'd have to use React or Vue.
	- However, while some specific bundles I work on will be adopting React for this reason, I'm not ready to do the same for NodeCG core.
	- I want to wait a bit longer to see where [HTML Modules](https://github.com/w3c/webcomponents/issues/645) ([Chrome Intent to Implement](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/ewfRSdqcOd8/w_Fr6rJ3DQAJ)) and https://github.com/Microsoft/TypeScript/issues/29432 lead to, and try to build on top of browser standards as much as possible. As neat as React is, it is not a standard, and I'm wary of committing NodeCG to it for that reason.

**Comment by Lange** [comment]
We've already migrated off of Polymer 2, and are now on Polymer 3. That should at least make this migration slightly easier for the frontend code.

**Comment by Lange** [comment]
I think I might just lock myself in my office for a week and try to bang this out for v2.0.
