### ISSUE TITLE
Can't get custom fonts loading on the latest version of Chrome

### ISSUE THREAD

**Issue by Forceh91** [nodecg/nodecg#440]
I'm having a lot of difficulting getting custom fonts to load when trying to apply them to custom child Polymer Elements (similar to a molecule in SGDQ2018 layouts). This has only happened since Chrome's latest update.

For example, I have the following:

```html
<dom-module id="omnibar-dual-message">
    <link rel="import" href="../../../../shared/fonts/avenir/stylesheet.css" type="css"/>
    
    <template>
    ...
</dom-module>
```

Which does not work. I have also tried:

```html
<dom-module id="omnibar-dual-message">
    <link rel="import" href="../../../../shared/fonts/avenir/import.html"/>
    
    <template>
    ...
</dom-module>
```

Again, with no results.

Am I just forgetting to do something really obvious when I'm trying to get fonts loading?

**Comment by Hoishin** [comment]
Does it work if you put the `<link>` element outside of `<dom-module>`?

**Comment by Forceh91** [comment]
I haven't tried that yet

**Comment by Forceh91** [comment]
Update @Hoishin - that did not work.

**Comment by Forceh91** [comment]
Using WOFF files for this worked in the end, I don't think it's an issue with NodeCG itself.
