### ISSUE TITLE
Distribution of NodeCG

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#451]
NodeCG is mainly distributed through `git` which brings you many unnecessary files.

Freshly cloned NodeCG consists of these files/folders:
```
4.0K	.dockerignore
4.0K	.editorconfig
4.0K	.eslintignore
4.0K	.eslintrc
 13M	.git
4.0K	.gitattributes
4.0K	.gitignore
 36K	.idea
4.0K	.jsdoc.json
4.0K	.travis.yml
4.0K	./AUTHORS
 40K	./CHANGELOG.md
4.0K	./CODE_OF_CONDUCT.md
4.0K	./CONTRIBUTING.md
4.0K	./Dockerfile
4.0K	./LICENSE
 12K	./README.md
4.0K	./bower.json
684K	./build
4.0K	./bundles
4.0K	./db
8.0K	./gulpfile.js
4.0K	./index.js
328K	./lib
100K	./media
804K	./package-lock.json
8.0K	./package.json
4.0K	./polymer.json
 12K	./schemas
8.0K	./scripts
284K	./src
1.6M	./test
220K	./tutorials
 32K	./types
 32K	./typetest
```
And total is 17M.

If you remove unnecessary files
```
4.0K	./AUTHORS
 40K	./CHANGELOG.md
4.0K	./Dockerfile
4.0K	./LICENSE
 12K	./README.md
4.0K	./bower.json
684K	./build
4.0K	./bundles
4.0K	./db
4.0K	./index.js
328K	./lib
100K	./media
804K	./package-lock.json
8.0K	./package.json
 12K	./schemas
284K	./src
 32K	./types
```
Total becomes 2.3M, which is about 13% of original size(!).

Since NodeCG itself isn't npm package or bower package, we need our own way to distribute the slimed package.

I think GitHub release would be easy and good solution, but I'm open to any good options

cc @Lange

**Comment by Lange** [comment]
I'm probably okay with this. Would these be what gets installed via `nodecg-cli`? If so, we'd need to re-write `nodecg-cli` to not use git, but to instead use these tarballs.

**Comment by Hoishin** [comment]
Yes using them in `nodecg-cli` would be the main benefit of using this way of distribution. I'll see if it's possible to include this in release process along with release notes.

**Comment by Hoishin** [comment]
The CI is setup for new releases. Now have to make a little script to create all releases in history, so it can be used in `nodecg-cli`.
Since it isn't easy to figure out which folder/files are required for each release in history, I will just pack the whole source code for previous releases. The future releases will have minimal files.

**Comment by CarlosFdez** [comment]
Editorconfig existing in the root folder caused some awkwardness when I was trying to write a bundle recently, as vscode was picking up the editorconfig and overriding auto-detect settings. So yeah that's a vote from me.

Of the files you listed though, isn't package.json necessary?

**Comment by Hoishin** [comment]
package.json is included in the original post’s list. If you were talking about package.json’s `files` field, you don’t have to specify some files because they are always included.

**Comment by Hoishin** [comment]
Yes I think so
