### ISSUE TITLE
Quick Start: You need to run npm install and bower install before launch

### ISSUE THREAD

**Issue by krisdahl** [nodecg/nodecg#476]
Just a heads up that the quick start instructions don't mention running `bower install` or `npm install`.

You'll get errors starting nodecg, and the dashboard pages won't load until you do.

**Comment by Lange** [comment]
The `nodecg setup` command is supposed to handle running `npm install` and `bower install`. If that command is not handling those functions, then there is potentially a bug in `nodecg-cli`.

**Comment by Hoishin** [comment]
Cannot reproduce this. `nodecg-cli` does run `npm install` and `bower install`.
