### ISSUE TITLE
HTML Imports are deprecated

### ISSUE THREAD

**Issue by daniellockard** [nodecg/nodecg#482]
Chrome has deprecated html imports, and will remove them ~June 2019. I think this might be related to polymer stuff primarily? 

https://www.chromestatus.com/feature/5144752345317376

**Comment by Lange** [comment]
Yep. However, the HTML Imports polyfill is pretty simple and lightweight, and is already loaded on the dashboard. The dashboard should continue working just fine after HTML Imports are removed from Chrome, as evidenced by the fact that the Dashboard already works in browsers which never supported HTML Imports to begin with, such as Firefox.

As for specific bundles, NodeCG does not require bundles to Polymer, and that's a decision up to each individual bundle author. If authors want to migrate to using a different library, they are free to do so at any time.

Long-term, we do plan to migrate NodeCG core away from Polymer. However, we have not decided what we will use in its place. And, given how well the dashboard itself currently works, I'm in no rush to re-write all of it just to avoid loading one small polyfill.

**Comment by daniellockard** [comment]
That's what I figured -- just noticed it in the chrome console and didn't see an existing bug. :)
