### ISSUE TITLE
Getting defaultValue of a replicant returns current value for some data types

### ISSUE THREAD

**Issue by zoton2** [nodecg/nodecg#486]
If you try to get the default value (`replicant.opts.defaultValue`) of certain replicants, for example if it an object, it will return the same as the current replicant instead. The default value needs some cloning when it's initialised.

**Comment by Seldszar** [comment]
I have two solutions:

- Cloning during the instantiation (nothing will change user-side)
- Using factories, like Vue.js does with objects, arrays, etc...
Example:
```javascript
const replicant = nodecgReplicant("defaultFactory", {
  defaultValue: () => ({ lorem: "ipsum" })
});
```

Both are equivalent but everything will depend of the design approach the project will choose.
