### ISSUE TITLE
Replicant assignments and operations can be emitted to clients out-of-order

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#489]
Consider the following extension code:

```js
const myArrayReplicant = nodecg.Replicant('my_array');
myArrayReplicant.value.push('foo');
myArrayReplicant.value = ['bar'];
```

After this code executes, the extension will have a value of `['bar']` for this Replicant.

However, although the assignment happened after the push, browser clients will get the assignment _before_ the push, meaning that browser clients will end up with a value of `['bar', 'foo']`.

Refreshing the affected browser pages will result in them getting updated to the correct value, because they re-request it from the server, which was indeed correct this whole time. That means that this bug is one which causes divergence between the server and clients, which is pretty bad.

-----

The root problem is that assignment is always emitted immediately, whereas mutation operations are delayed until at least the next tick. The fix here is to ensure assignment gets queued in the same manner as mutation operations.

**Comment by Hoishin** [comment]
@Lange Can we close this now?

**Comment by Lange** [comment]
Yep!
