### ISSUE TITLE
Frequently-updated Persistent Replicants can kill SSDs

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#493]
Consider the GDQ bundles. These graphics packages have multiple Persistent Replicants which update at 60-100hz. This means they are writing to SSDs constantly, at a very high rate, because NodeCG's implementation of Persistence is currently pretty naive, and it will write every single change to disk.

This is actually kind of dangerous, because it increases the odds that an SSD will fail during a show, due to how much wear this puts on an SSD's write cycles.

One solution might be to reduce the rate at which Persistence writes to the disk, but... what if you _need_ certain Replicants to always have the most up-to-date persisted value possible?

Do we add a new option, which defines how frequently a given Replicant will save its Persisted value to disk? What would the default value of this option be?

Do we also try to make NodeCG save all Replicants to disk before exiting? Does that help guard against crashes?

**Comment by Seldszar** [comment]
I was thinking about throttling for #488, so I think this solution with a final persistence at SIGINT/SIGTERM could be a good idea.

**Comment by Lange** [comment]
I think I like throttling + final persistence on program exit as well. However, I think I might want an escape hatch for users to be like "no really, this Replicant is mission-critical, and we must always have the latest value persisted to disk". Maybe the benefits from such an override aren't worth the API complexity though.

**Comment by Seldszar** [comment]
Like being able to change  the persistence interval? Doable, and if the Replicant is mission-critical, simply set the interval to 0 for example.

```javascript
const replicant = nodecg.Replicant("lorem", {
  persistenceInterval: 0,
});
```

With that, users have control over the persistence process.

**Comment by Lange** [comment]
Yeah something like that sounds good to me. 👍
