### ISSUE TITLE
Consider porting NodeCGElements to Stencil

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#495]
My original goal with [NodeCGElements](https://github.com/NodeCGElements) was to provide a framework-agnostic set of re-usable components to be used in Dashboards (a few of them are also useful in Graphics, but they're mostly aimed at Dashboard usage). I wanted to use Web Components to achieve this goal, because they're a browser standard and I figured that meant that the big frameworks like React and Vue would be able to interop with them.

This ended up not being the case, for several reasons:
- I used Polymer to author these WCs, which turned out to be chock-full of leaky abstractions.
- Vue, React, Angular, and the other big frameworks only relatively recently began having good stories for WC interop (i.e., consuming Web Components in a React app. I'm not currently worried about in interop in the other direction).

As a result, NodeCGElements has languished and not seen much use. Right now it's simply not feasible nor advisable for someone writing a bundle in React/Vue/Svelte/etc to use any of these NodeCGElements -- they're just too leaky and not portable enough.

But, now that a few years have passed, it seems that my original goal is more attainable. Specifically, a tool called [Stencil](https://stenciljs.com) aims to achieve _exactly_ what I am describing. There's an article here explaining the philosophy behind why Web Components, despite their many flaws, are the best choice for creating a Design System which can be used in as many frameworks as possible: https://ionicframework.com/blog/build-your-next-design-system-with-web-components/

I need to do more research on Stencil to see if it really is the solution I'm hoping for, but I'm cautiously optimistic and am interested in hearing others' thoughts. Being able to provide a lightweight set of easy-to-use legos that can be used in any framework (or no framework) is a dream of mine.

**Comment by Lange** [comment]
For those curious, Stencil does seem to have a story for TypeScript support and outputting `d.ts` files: https://stenciljs.com/docs/typed-components

**Comment by Lange** [comment]
https://custom-elements-everywhere.com/ is also a good resource to learn about how various frameworks achieve interop with WCs.

**Comment by Lange** [comment]
More relevant reading:

- [Blog post announcing the (very recent) release of Stencil v1.0](https://ionicframework.com/blog/introducing-stencil-one-1-0-0/)
- [StencilDS](https://stenciljs.com/design-systems), which is their private enterprise solution for authoring an entire Design System using Stencil, and outputting framework-specific bindings.

I was unaware that the Stencil project was split into these two halves: a basic open-source core, and a non-free enterprise offering. A lot of the things I want are only available in the enterprise offering.

**Comment by Hoishin** [comment]
OK I like this. Stencil looks way more promising than I used to think. I'll have to play with this sometime haha

**Comment by mkrl** [comment]
While Stencil does look interesting and definitely benefiting the future of NodeCGElements, I would say it may be worth investing just a bit of time into porting existing components to npm, the same way that Polymer itself did. HTML imports are already [deprecated](https://www.chromestatus.com/features/5144752345317376). 
Considering NodeCG elements extend Polymer paper-[thing], I imagine this won't take too much effort. I'm pretty sure you can use Polymer components with other frameworks, even though it's not the best thing to do. With ES6 modules in place of HTML imports we could have both easy distribution via npm, availability for those who wish to develop their panels without compiling (` <script type="module">`) and for those who use something like Babel together with a framework of choice (`import`).

**Comment by Lange** [comment]
@mkrl to clarify, are you suggesting a two-step approach?:

1. port existing elements to Polymer 3, so that they can be published to npm
2. with that band-aid solution in place, investigate Stencil

**Comment by mkrl** [comment]
Yes, exactly. We still need something to replace core dashboard elements that may stop working in modern  Blink browsers in February 2020 (they were previously supposed to be gone by May 2019, if I'm not mistaken). Either way, I would say it's worth at the very least taking a look at the process of porting everything to Polymer 3 and comparing with approximate amount of effort to implement the Stencil solution.

**Comment by Lange** [comment]
@mkrl The current `NodeCGElements` will not necessarily stop working when HTML Imports are removed from Chromium. The HTML Imports polyfill itself is pretty small, and not a big deal to import if already importing all of Polymer 2 to use the existing elements.

I'm pretty cold on the idea of porting twice, it's just so much work. There is an "automated" tool to port Polymer 2 code to Polymer 3, but it [literally doesn't work](https://github.com/Polymer/tools/issues/757#issuecomment-444490611).

**Comment by mkrl** [comment]
@Lange that's fair. Actually, I have just taken a look at Stencil and it's seems pretty straightforward to use. 

...apart from extending existing components. With Polymer we had an ecosystem to build on (even though I'm entirely unfamiliar with how Polymer works, to be honest). A quick try of building something on top of existing component from [material web](https://github.com/material-components/material-components-web) resulted in a failure. 

Stencil team did [explicitly state](https://github.com/ionic-team/stencil/issues/1060#issue-356651082) that inheritance from any imported class is no longer an option and will never be. 
There are some "non-native" workarounds for sure. At the very least, we could simply write everything from scratch and only import CSS, but that just seems unpractical.

**Comment by Lange** [comment]
@mkrl For the existing ecosystem, that would be the Ionic framework, which is what birthed Stencil to begin with: https://ionicframework.com/docs/components

I was unaware that Stencil completely did not support the concept of class inheritance in general. This is indeed surprising. [This comment](https://github.com/ionic-team/stencil/issues/1060#issuecomment-486655066) on that issue thread says they have other best practices to offer, but there was no followup. I'd love to find and read those guidelines on how to cope without class inheritance, if they did indeed ever get written.

Since a lot of NodeCGElements is basically just "take existing component and wrap it with some NodeCG-specific logic", I agree that the lack of inheritance is really concerning and could be a showstopper for our adoption of Stencil.

**Comment by FRSgit** [comment]
@Lange There is also other, still opened issue on stencil repo about the topic: https://github.com/ionic-team/stencil/issues/1382

But, after few talks with stencil guys on their slack channels I got the info that they do not intend to support class extending and the only solution they can provide is using composition pattern instead (which is not great both from performance, accessibility and SEO perpective, but well). And unfortunately nobody can answer the question why exactly they chose to stick so hard to this principle :<

**Comment by Lange** [comment]
At this point, it seems unlikely that Stencil will end up working out great for us right now. We can re-open this later if we change our minds.
