### ISSUE TITLE
Write tutorial for using p5.js (Processing) to make graphics

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#499]
[Processing.js](http://processingjs.org/) aims to be more accessible to people without much programming experience, and I'd like to provide some guidance for folks on how to use it in the context of NodeCG. I think this would be a great way to get more people into NodeCG.

**Comment by Lange** [comment]
Err maybe I was thinking of [p5.js](https://p5js.org/)? I think `process.ing.js` is an older, separate port.

**Comment by Hoishin** [comment]
Processing.js was deprecated last year in favor of p5.js. I'm not familiar with the difference but probably should go with p5.js instead.
https://github.com/processing-js/processing-js/#%EF%B8%8F-this-project-has-been-archived-%EF%B8%8F
https://p5js.org/

**Comment by EwanLyon** [comment]
Thought I had already posted this here but here's my basic repo: https://github.com/EwanLyon/ncg-p5-tutorial

**Comment by Lange** [comment]
@EwanLyon Cool! Mind creating a PR which adds a tutorial markdown file for this which briefly explains the integration and links to your repo?

**Comment by Lange** [comment]
Upon further thought, the right place for the `ncg-p5-tutorial` bundle is probably the https://github.com/nodecg/nodecg-simple-examples repo. So, you'd open two PRs:

- one here which adds a `tutorial` markdown file
- one on nodecg-simple-examples which adds your bundle

**Comment by Lange** [comment]
This is done, forgot to close this
