### ISSUE TITLE
Use Ajv for JSON schema validation

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#502]
Pros
- (At least it says) it's faster
- Well maintained
- [A lot of options](https://github.com/epoberezkin/ajv#options) to make more use of JSON schema
  - personally interested in type coercion
- Allows newer schema specification

Cons
- Might break something

**Comment by Lange** [comment]
@Hoishin d'you think this is a high-value thing that we should aim to do for v2.0?

**Comment by Hoishin** [comment]
I think so. We can benefit enough from perfomance and newer spec support. Also even better if we can fix the bug (found or not found).

**Comment by silltho** [comment]
i was working on #375 and faced and issue with the current validator tv4. It wasn't recognising some of the needed schema definitions like if/then/else. So to complete #375 in a proper manner i'll first work on using ajv for the schema validation.
