### ISSUE TITLE
Error for missing "version" field in package.json happens only when opening graphics

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#503]
```
UNCAUGHT EXCEPTION! NodeCG will now exit.
Error: Invalid value rejected for replicant "graphics:instances" in namespace "nodecg":
        Field "0.bundleVersion" is required
```

This error should be thrown when NodeCG is launched, or it shouldn't be thrown at all.

**Comment by Lange** [comment]
I vote it should be thrown on startup, because this field is indeed needed
by the Graphics Registration system.

**Comment by Seldszar** [comment]
Does the error should be thrown when at least one graphics exists in the bundle or all the time?

**Comment by Lange** [comment]
Probably all the time? Enforcing that bundles have a `version` field seems
like a reasonable thing to me, but I'm opening to differing opinions.

**Comment by Hoishin** [comment]
I think it should just throw in any case to fix this issue.

But I'd like to revisit if using `version` field in package.json is reasonable, regardless of this issue. The `version` field is primary to define version of published npm package, and bundles are not usually npm packages, and as a result it's just left with a same version.

**Comment by Seldszar** [comment]
Maybe a `nodecg.version` field, fallbacking to `version` for backward compatibility, could be a solution?
