### ISSUE TITLE
Assignable soundCues aren't properly updating their associated files in mixer

### ISSUE THREAD

**Issue by ghost** [nodecg/nodecg#505]
In cases where a soundCue is assignable, changing the file it uses through it's drop-down menu in the mixer doesn't actually affect it's associated Replicant. This causes the soundCues to be either stuck on Default if a defaultFile is present, or None if one isn't defined to begin with or defined after the specific Replicant for the soundCue was created.

![pic](https://user-images.githubusercontent.com/44181885/61586780-ef769880-ab49-11e9-8e6b-c2580a6d40c7.gif)

**Comment by ghost** [comment]
Got around to digging into what's going on, pinpointing where this started to begin with. Found it started being an issue with [`0dafe4e`](https://github.com/nodecg/nodecg/commit/0dafe4eda7306bcfaffbd3534b2e1c99c89cc9a0), in which the `ncg-sound-cue` element switched it's `select` dropdown with the `ui-select` element. Switching it back in NodeCG `1.5.0` allows for soundCue replicants to properly update their `file` property, persisting the change as intended. I wouldn't really call this a fix more than a workaround, though. My knowledge ends here however, as I'm not too familiar with the inner workings of this system at the moment.

**Comment by Lange** [comment]
Thanks for finding where this regression happened! Hopefully someone can dedicate some time towards getting this patched up.

**Comment by bitowl** [comment]
`ui-select` does not expose the `on-change` event and the `selectedOptions` property needed by `ncg-sound-cue`.

I have no idea how to correctly expose those with Polymer though, so my current workaround is to simply use a styled `select` as well.

**Comment by ghost** [comment]
Patched with nodecg/nodecg#537, should be good now
