### ISSUE TITLE
NodeCG clients should be notified when disconnected from NodeCG server

### ISSUE THREAD

**Issue by jhobz** [nodecg/nodecg#506]
Per a discussion in Discord, a few useful methods were proposed in case a client needs to update the view upon disconnections:
* `nodecg.on()` for listening to the following events emitted by `nodecg`:
  * `connect` - Connected to server
  * `disconnect` - Disconnected from server
  * `reconnect`* - An attempt was made to reconnect | Successfully reconnected after a disconnection
* `nodecg.isConnected()` for checking current connection status.

Additionally, a `nodecg.connectedClients` property on the server could be useful for checking client status.

---

*Discussion requested: should this event be included at all? If so, which of the two proposed would be preferred?

**Comment by Lange** [comment]
Let's explore this for v2.0, and either commit to adding these things or explain why they're not necessary.

**Comment by alvancamp** [comment]
This type of data can be accessed from the `nodecg.socket` property, which exposes an instance of `socket.io-client`. NodeCG v1.x uses Socket.IO v2, and the soon-to-be merged (I swear) `refactor/ts` branch uses v4.
