### ISSUE TITLE
Remove Zeit pkg support

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#518]
1. It requires multiple obtuse workarounds in NodeCG itself to support.
2. It can't be code signed, which means Zeit pkg output basically can never run on macOS, which is super strict about code signing.
3. Using an exe bundler like pkg or nexe provides nearly no value for NodeCG. We get almost the same thing by just placing `node.exe` in the same folder and zipping the whole thing up instead.

Thoughts @Hoishin?

**Comment by Hoishin** [comment]
Overall I agree. It would help to provide a guide to move out of zeit.

Also ultimately you could just place a .bat file (or .sh for other platform) to double click instead of zeit.

**Comment by Lange** [comment]
I'll start work in a PR in a bit to remove the Zeit-specific stuff from NodeCG and provide a migration guide. Since this is a breaking change, it'll have to go into the 2.0-dev branch, which also has one other breaking change in it already. We'll then need to figure out if these 2 breaking changes are enough reason to justify a release, or if we have anything else on the near horizon (i.e. less than a month away) that we think will also be a breaking change. I personally don't have anything else in mind that I could get done any time soon.

**Comment by Lange** [comment]
This is done in #520 and will be part of v2.0
