### ISSUE TITLE
Instant messaging in dashboard

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#55]
With the advent of synced variables, it is now feasible for multiple operators to use the dashboard simultaneously. To facilitate collaborative production, the dashboard should feature a chatroom of sorts that all operators can use to communicate with one another.

My current design idea includes having the chat be shown/hidden by a button on the navbar. When shown, a small chat window would descend the navbar. If the chat box is selected/active, new messages will make no notification. If the chat box is not selected/active, it (and maybe the window) should flash. If the chat box is hidden, a counter should be shown next to the chat button on the nav bar displaying the number of unread messages, and the window should flash. Sounds should be considered as well. Notification settings should be adjustable on a per-user basis.

A transient history could also be stored in memory (not persisted to disk), much like Steam messages. Perhaps the last 25 messages, such that an accidental refresh won't wipe everything.

**Comment by Lange** [comment]
In retrospect, this probably isn't a good idea. No reason to compete with other, far better dedicated messaging platforms.

**Comment by thesupremecommander** [comment]
I disagree. Even if the chat embedded within the dashboard were basic, it would allow for one less window to be open and allow for communication that isn't reliant on any other service.

However, this functionality might be better suited for a bundle and not core.
