### ISSUE TITLE
ENOENT Error on Asset Upload - Solved -> Space in asset name

### ISSUE THREAD

**Issue by lost-hope** [nodecg/nodecg#577]
Hello,
When i try to upload a PNG as an Asset i get an ENOENT error on the console. 

The important part of my bundle package.json :
`"assetCategories": [
{
        "name": "sprite ",
        "title": "sprite",
        "allowedTypes": ["png"]
      }`

The error message on the console:
`[Error: ENOENT: no such file or directory, open 'E:\Twitch\nodecg\assets\sprite-animator\sprite\idle.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\Twitch\\nodecg\\assets\\sprite-animator\\sprite\\idle.png',
  storageErrors: []
}`

In explorer i can see the folder, but not the file (cause it is not uploaded yet)

My system is running Windows 10, if that is important.

**Comment by zoton2** [comment]
Is it something to do with the space in your bundle name maybe? I see it says `"sprite "` with an extra space at the end, unless that was an issue with your copy/paste.

**Comment by lost-hope** [comment]
That fixed it. 
I did check if there is a german umlaut in the path (my name contains one) or other special things but not a simple space.
Thank you so much
