### ISSUE TITLE
Convert nodecg to act as a command line tool

### ISSUE THREAD

**Issue by MattMcNam** [nodecg/nodecg#6]
A new user shouldn't have to grab the repository to use nodecg.  

The current goal workflow is:
- `npm install nodecg`
- `nodecg init my-overlay`
- `cd my-overlay`
- `nodecg start`

The folder `my-overlay` should only contain a config file, and a packages folder.

**Comment by Lange** [comment]
Implemented in [nodecg-cli](https://github.com/nodecg/nodecg-cli), will work with the upcoming NodeCG 0.4.0.
