### ISSUE TITLE
Is it possible to divide sqlite file by bundles?

### ISSUE THREAD

**Issue by bannin** [nodecg/nodecg#677]
Before v2.0.0, deleting db/bundle-name folder was a good way to reset data of a specific bundle.
But now, all bundle data is saved into a single sqlite file. so I don't use this way anymore.
Is it possible to divide a sqlite file by bundles? 
I'm not familiar with SQLite, so I don't judge this way is the best solution...

**Comment by duncte123** [comment]
You can just open the database in a free database browser like tableplus (or datagrip if you have a jetbrains license) and delete it that way. 
The single database was probably done with a specific reason. @alvancamp would you happen to know this reason?

**Comment by bannin** [comment]
thank you for your help!
I will try https://sqlitebrowser.org/
