### ISSUE TITLE
npm reports vulnerabilities in TypeORM dependencies

### ISSUE THREAD

**Issue by Wataru343** [nodecg/nodecg#718]
Recently, when I ran npm audit on our project, it was detected that there is a security vulnerability in a dependency module used by TypeORM.
Therefore, I believe it would be best to update to the latest version.
In the latest version, xml2js has been removed.

```
npm audit            
# npm audit report

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/xml2js
  typeorm  0.1.0-alpha.1 - 0.3.14-dev.daf1b47 || >=0.3.20-dev.73e3b49
  Depends on vulnerable versions of xml2js
  node_modules/typeorm
    @nodecg/types  *
    Depends on vulnerable versions of typeorm
    node_modules/@nodecg/types
    nodecg  >=2.0.0
    Depends on vulnerable versions of typeorm
    node_modules/nodecg
```

**Comment by Hoishin** [comment]
I'm planning to replace typeorm with something else soon

**Comment by Wataru343** [comment]
That sounds good.
I'll close this issue because I don't need it.

**Comment by Hoishin** [comment]
Turned out switching away from TypeORM is more involving that I expected. I'll upgrade the version for now.

**Comment by Hoishin** [comment]
Fixed by https://github.com/nodecg/nodecg/pull/722
