### ISSUE TITLE
Make a statement.

### ISSUE THREAD

**Issue by from-the-river-to-the-sea** [nodecg/nodecg#730]
I'm getting closer.

You cannot run.

Israel will lose.

Palestine will be free.

History will judge this time.

Cowardice will be [ENCRYPTED].

**Comment by Hoishin** [comment]
Hey, I have been finding it frustrating that none of OSS community is giving focus on Palestine situation that they have done for BLM and Ukraine. If we can go ahead with this, is there any good educational resource to link to increase awareness?

**Comment by Hoishin** [comment]
Closing in favour of #731
