### ISSUE TITLE
package management

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#95]
NodeCG needs a package manager.

It should be based on npm, because npm is really good and we'll never make anything better than it.

Every piece of npm is open source, and we know that `npm` will be in every user's PATH. Our first approach should be to make our own registry, and have [nodecg-cli](https://github.com/nodecg/nodecg-cli) wrap `npm` as needed to interact with our registry. See [apm](https://github.com/atom/apm) for an example of this.

**Comment by Lange** [comment]
There don't seem to be any turnkey solutions for hosted public npm registries. Plenty of people are willing to take your money (a lot of it) for private registries and other enterprise solutions, but nobody seems to be offering hosting for public registries.

Our best bet seems to be to self-host [sinopia](https://www.npmjs.com/package/sinopia). I don't know what kind of server/bandwidth resources we'll need to reliably host our own registry, but I suspect they could be significant. We will absolutely need to go with a hosting solution that lets us start small and easily scale up whenever we need to. Incrementally ramping up the horsepower of our registry will be crucial, lest we go broke.

**Comment by Lange** [comment]
It appears I have spoken too soon about the lack of public hosting options. Gemfury seems to offer a plan that would allow us to have unlimited public packages for $10/mo [Link](https://gemfury.com/plans/personal).

**Comment by Lange** [comment]
I've fired off an email to Gemfury asking them to clarify some of the wording on their plans. I'll post again when I have a response.

**Comment by Lange** [comment]
The Gemfury plans unfortunately are not viable, as they limit the number of people who can publish to the registry.

However, I got an alternative offer in the email response from Gemfury that I am currently investigating.

**Comment by Lange** [comment]
I've yet to hear back from Gemfury after our last email.

I've put more thought to [sinopia](https://www.npmjs.com/package/sinopia), and I no longer think it is a valid choice for a scalable public registry. There seems to be no way to easily scale sinopia across multiple servers, and it stores all packages on the local filesystem.

Aside from GitHub's [apm](https://github.com/atom/apm), I can't find any other examples of organizations hosting their own public registries, especially not a small team like us. I'm worried that the infrastructure for small teams to host public registries might not exist.

**Comment by Lange** [comment]
Over one year later and no further public statements have been made by npm about the Ecosystems feature. Might need to re-think the approach here.

**Comment by madmatt** [comment]
What do you need a package manager for? You've already got `nodecg install` to install bundles, which (I'm assuming) checks the bundle dependencies to make sure the versions of nodecg and other installed bundles are appropriate before installing.

Bundle testing (#96) is a little more complex, but you could automate a lot of the pain by creating a `nodecg test [optional_bundle_name]` command or similar that (if a bundle name is provided) only loads that bundle and its dependencies for nodecg startup, and runs tests inside <bundle_name/tests> folder or similar. The other thing to consider is that largely bundles should be ignorant of the nodecg core (in that they should be unit testing isolated functionality, not testing that nodecg is for example displaying a browser page with the appropriate graphic being rendered)... though you'd want more complex systems to have behavioural / end-to-end testing across them I'd guess (AGDQ/SGDQ bundles spring to mind)

**Comment by Lange** [comment]
`nodecg install` does not currently do any validation such as checking the NodeCG version or bundle dependencies, though it could be updated to do that and throw very clear, helpful error messages.

At this point I think I've sort of lost the thread on _why_ I wanted more structured package management for NodeCG bundles, but I think the idea I was chasing was that I wanted npm to be the primary way that bundle authors publish their code, such that they are forced into updating the version number of their bundle whenever they make a change. This then makes the semver information in each bundle more useful, and that creates an ecosystem where testing is more meaningful. This quote from #96 illustrates my mindset at the time:
>Right now, bundle dependencies aren't even versioned. This makes it impossible to automatically test bundles that depend on other bundles, unless those dependencies are bundled in the repo (that's a dumb sentence). For this type of testing to work, we need to have stricter versioning of bundles. This means having a proper package manager (#95).

(Since then, the `bundleDependencies` field has changed from being a simple array of bundle names to being an object with `bundleName`/`bundleVersion` pairs, just like `dependencies` in `package.json`)

Bundle authors _can_ publish to npm right now and they _can_ use semver, but there's nothing really pushing them into doing that aside from their own discipline. I'd like NodeCG to have a clearly defined "best path" that it gently guides developers onto.

**Comment by madmatt** [comment]
Yeah, this seems more like something that could be handled with some brief documentation on "How to use semver with nodecg", which is basically "Understand semver, apply it like you would any other package, in the future nodecg may expect that you are using semver for updating bundles".

I think using semver appropriately makes a lot more sense for an extension than it does for a bundle necessarily. For example, `lange-notify` probably just needs to depend on a particular semver'd version of nodecg correctly, whereas I might make a nodecg extension that defines a bunch of replicants for some API data that other bundles can hook to update some graphics they have (e.g. SupportClass/lfg-twitchapi, which from a quick look does nothing by itself, but exposes an API for other bundles to draw data from). These are more important to ensure developers use semver correctly, so that other bundle creators can make sure they don't always break whenever they pull the latest patch release...

That's my rambling 2c at least - a brief intro somewhere that mentions it, and especially calls it out for extensions/API helpers.

**Comment by Lange** [comment]
zkat/pacote is relevant to this. From what I can tell, it provides a means of downloading npm-compatible packages and extracting them to an arbitrary directory. This could be used to augment `nodecg-cli`'s `install` command to pull from npm directly, which would then give us a reason to encourage bundle authors to publish to npm.

**Comment by Lange** [comment]
[zkat/npm-pick-manifest](https://github.com/zkat/npm-pick-manifest) is also relevant to this.

Between `npm-pick-manifest` and `pacote`, we might have all the pieces we need to build a workflow centered around publishing bundles to npm.

**Comment by Lange** [comment]
This issue is old, vague, and has never had solid direction. Closing.
